### ISSUE TITLE
Still Interested in working on this?

### ISSUE THREAD

**Issue by NapsterInBlue** [avlaskin/QuickLabel#1]
Was actually sitting down to start in on a very similar idea for a library, but instead came across this repository during [a cursory scan through PyPI](https://pypi.org/search/?q=image+label&page=5)-- love the work you've done with this.

Was hoping to fork and add a few more features, but was wondering if you'd be open to a PR down the road or available to answer questions along the way.

Cheers!

**Comment by avlaskin** [comment]
Hi Nick, absolutely, let's extend it if you like. :)

**Comment by NapsterInBlue** [comment]
Hey, awesome!

Gonna close this issue out and open others for more targeted conversations. Lmk if you'd rather use some other avenue to get on the same page
