### ISSUE TITLE
Global Interface

### ISSUE THREAD

**Issue by NapsterInBlue** [avlaskin/QuickLabel#2]
Had success playing with the UI after cloning the repo locally. 

But am I missing some command line functionality that I'd get from pip installing? Got `v1.0.2` off PyPI, but couldn't get it to work *globally* like you would, say, [cookiecutter](https://github.com/audreyr/cookiecutter) or [jupyter notebooks](https://github.com/jupyter/notebook).

**Comment by avlaskin** [comment]
I c, it's because of internal import should point to the package and file, not just to the package.
